export const environment = {
  production: false,
  platformProviderApiBaseUrl: 'http://localhost:3000/api/v1',
  platformProviderWorkshopsEndpointPath: '/workshops',
  platformProviderUsersEndpointPath: '/users',
  platformProviderPasswordRecoveryTokensEndpointPath: '/password_recovery_token',
  platformProviderCustomersEndpointPath: '/customers',
  platformProviderVehiclesEndpointPath: '/vehicles',
  platformProviderWorkBaysEndpointPath: '/work_bays',
  platformProviderAppointmentsEndpointPath: '/appointments',
  platformProviderObd2DevicesEndpointPath: '/obd2_devices',
  platformProviderVehicleDtcAlertsEndpointPath: '/vehicle_dtc_alerts',
  platformProviderIotSnapshotsEndpointPath: '/iot_snapshots',
  platformProviderWorkOrdersEndpointPath: '/work_orders',
  platformProviderWorkOrdersTasksEndpointPath: '/work_order_tasks',
  platformProviderQuotesEndpointPath: '/quotes',
  platformProviderProductsEndpointPath: '/products',
  platformProviderInventoryMovementsEndpointPath: '/inventory_movements',
  platformProviderVouchersEndpointPath: '/vouchers',
  platformProviderOutboxMessagesEndpointPath: '/outbox_messages',
  platformProviderPaymentsEndpointPath: '/payments',

};
